### ISSUE TITLE
Booting problems (TFTP)

### ISSUE THREAD

**Issue by MetallDoktor** [FOGProject/fogproject#229] opened 2018-02-06 08:25 UTC
Hello!

I've installed FOG recently and faced the next problem: when I try to boot Windows PC via network, the following can be seen...  

![tftp](https://user-images.githubusercontent.com/33860184/35847958-4dc018ee-0b2d-11e8-902f-919a02f071f9.png)

...and then it just boots into HDD (Windows 10), leaving in FOG server syslog "in.tftpd[752]: tftp: client does not accept options".

FOG and Windows PC are in one network. Install settings below:

 * Base Linux: Debian
 * Detected Linux Distribution: Ubuntu
 * Server IP Address: 10.0.182.33
 * Server Subnet Mask: 255.255.255.0
 * Interface: enp1s0f1
 * Installation Type: Normal Server
 * Internationalization: 0
 * Image Storage Location: /images
 * Using FOG DHCP: Yes
 * DHCP router Address:

I've already checked your Troubleshoot TFTP guide (https://wiki.fogproject.org/wiki/index.php?title=Troubleshoot_TFTP), all OK.

Before that I tested FOG on esx virtual servers (for FOG itself and host to PXE), all worked fine. I've registered host and uploaded/deployed images from it successfully. 

Is there anything that can be done in such case? 

Big thanks in advance!

**Comment by mastacontrola** [comment] 2018-02-06 08:56
Is hide menu or no menu, by chance, enabled?

Does this happen on all your machines, or just this one, or just this model?

What version of fog are you running?

The tftp message you’re seeing is normal. It basically just means the data tftp is send to the client is not understood/accepted.

I realize there’s a lot of questions and all, just want to understand the issue more completely.

**Comment by MetallDoktor** [comment] 2018-02-06 09:04
1) If I understood you correctly: iPXE Boot Menu -> "no menu" and "hide menu" unchecked.
2) This is the only machine (described) which FOG is working with. No more, physical or virtual.
3) 1.4.4, last one from fogproject.org

**Comment by mastacontrola** [comment] 2018-02-06 09:08
Are the machines booting UEFI, or BIOS? What bootfile are you sending for pxe booting?

**Comment by MetallDoktor** [comment] 2018-02-06 09:16
It's usual BIOS. Bootfile? I believe, default.ipxe, as shown on the screenshot... Am I wrong?

**Comment by mastacontrola** [comment] 2018-02-06 09:27
The bootfile is the file pxe sends to the machine first. This would be something like:
ipxe.pxe
undionly.kpxe
undionly.kkpxe

**Comment by MetallDoktor** [comment] 2018-02-06 09:39
Looking in dhcpd.conf, I think it's undionly.kkpxe.

class "Legacy" {
        match if substring(option vendor-class-identifier, 0, 20) = "PXEClient:Arch:00000";
        filename "undionly.kkpxe";
    }
    class "UEFI-32-2" {
        match if substring(option vendor-class-identifier, 0, 20) = "PXEClient:Arch:00002";
        filename "i386-efi/ipxe.efi";
    }
    class "UEFI-32-1" {
        match if substring(option vendor-class-identifier, 0, 20) = "PXEClient:Arch:00006";
        filename "i386-efi/ipxe.efi";
    }
    class "UEFI-64-1" {
        match if substring(option vendor-class-identifier, 0, 20) = "PXEClient:Arch:00007";
        filename "ipxe.efi";
    }
    class "UEFI-64-2" {
        match if substring(option vendor-class-identifier, 0, 20) = "PXEClient:Arch:00008";
        filename "ipxe.efi";
    }
    class "UEFI-64-3" {
        match if substring(option vendor-class-identifier, 0, 20) = "PXEClient:Arch:00009";
        filename "ipxe.efi";
class "SURFACE-PRO-4" {
        match if substring(option vendor-class-identifier, 0, 32) = "PXEClient:Arch:00007:UNDI:003016";
        filename "ipxe7156.efi";
    }
    class "Apple-Intel-Netboot" {
        match if substring(option vendor-class-identifier, 0, 14) = "AAPLBSDPC/i386";
        option dhcp-parameter-request-list 1,3,17,43,60;
        if (option dhcp-message-type = 8) {
            option vendor-class-identifier "AAPLBSDPC";
            if (substring(option vendor-encapsulated-options, 0, 3) = 01:01:01) {
                # BSDP List
                option vendor-encapsulated-options 01:01:01:04:02:80:00:07:04:81:00:05:2a:09:0D:81:00:05:2a:08:69:50:58:45:2d:46:4f:47;
                filename "ipxe.efi";
            }
        }
    }

**Comment by mastacontrola** [comment] 2018-02-06 22:09
Can you explain what the problem is more directly?
What I can gather, you have one system that works, and that's it? Everything else the display doesn't happen?

**Comment by MetallDoktor** [comment] 2018-02-07 08:18
Problem is described: when I network boot Windows PC, I expect to see FOG menu for host registration, uploading/deploying images etc. But instead of it system just boots into the hard drive after showing me all of that OK messages. It doesn't point to any errors so I can't figure out the reason. There are two physical machines: FOG server itself and Windows PC to image.

Maybe you need some more logs or smth? Or I believe I don't fully understand what you mean by "more directly".

**Comment by mastacontrola** [comment] 2018-02-08 03:14
Is it immediately after the "ok" messages, or does some seconds go by then it boots to windows?

**Comment by MetallDoktor** [comment] 2018-02-08 05:34
Immediately, right after the last message.

**Comment by Sebastian-Roth** [comment] 2018-09-29 21:53
@MetallDoktor Has this ever been solved?

**Comment by Sebastian-Roth** [comment] 2018-11-27 22:05
Closing the issue now as we don't have enough information to help and fix this case.

**Closed by Sebastian-Roth** 2018-11-27 22:05 UTC
