### ISSUE TITLE
Installnotes for Archlinux

### ISSUE THREAD

**Issue by boban-dj** [FOGProject/fogproject#134] opened 2016-10-10 17:36 UTC
Just sharing some info when installing in clean Archlinux install.
After theses needed adjustments the installfog.sh script works as expected.

`uname -a`: Linux archz800 4.4.24-1-lts
`php -version`:  PHP 7.0.11 (cli) (built: Sep 16 2016 18:52:44) 
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies

## Needed before installfog.sh
These packages are not installed by the config.sh in the fogproject/lib/arch
		`pacman -S bc`
		`pacman -S php-apache`

## Mariadb (mysqld.service)
- problem starting mysqld.service from the installfog.sh, so I did it manually before the installfog.sh

		`sudo pacman -S mariadb`
then run:

		`sudo mysql_install_db --user=mysql --basedir=/usr --datadir=/var/lib/mysql`

## Httpd.conf (httpd.service)

location config file `/etc/httpd/conf/httpd.conf`

Note:
If you have added the following lines to httpd.conf, remove them, as they are no longer needed:

		LoadModule php7_module modules/libphp7.so
		Include conf/extra/php7_module.conf

enable the `proxy_html_module`

		LoadModule proxy_html_module modules/mod_proxy_html.so

This include is already set in the default httpd.conf from Archlinux, so check it in your config.

`Include conf/extra/proxy-html.conf`

other enabled modules:

                LoadModule authn_file_module modules/mod_authn_file.so
		LoadModule authn_core_module modules/mod_authn_core.so
		LoadModule authz_host_module modules/mod_authz_host.so
		LoadModule authz_groupfile_module modules/mod_authz_groupfile.so
		LoadModule authz_user_module modules/mod_authz_user.so
		LoadModule authz_core_module modules/mod_authz_core.so
		LoadModule access_compat_module modules/mod_access_compat.so
		LoadModule auth_basic_module modules/mod_auth_basic.so
		LoadModule socache_shmcb_module modules/mod_socache_shmcb.so
		LoadModule reqtimeout_module modules/mod_reqtimeout.so
		LoadModule include_module modules/mod_include.so
		LoadModule filter_module modules/mod_filter.so
		LoadModule proxy_html_module modules/mod_proxy_html.so
		LoadModule mime_module modules/mod_mime.so
		LoadModule log_config_module modules/mod_log_config.so
		LoadModule env_module modules/mod_env.so
		LoadModule headers_module modules/mod_headers.so
		LoadModule setenvif_module modules/mod_setenvif.so
		LoadModule version_module modules/mod_version.so
		LoadModule proxy_module modules/mod_proxy.so
		LoadModule proxy_fcgi_module modules/mod_proxy_fcgi.so
		LoadModule slotmem_shm_module modules/mod_slotmem_shm.so
		LoadModule ssl_module modules/mod_ssl.so
		LoadModule mpm_prefork_module modules/mod_mpm_prefork.so
		LoadModule unixd_module modules/mod_unixd.so
		LoadModule status_module modules/mod_status.so
		LoadModule autoindex_module modules/mod_autoindex.so
		<IfModule !mpm_prefork_module>
			#LoadModule cgid_module modules/mod_cgid.so
		</IfModule>
		<IfModule mpm_prefork_module>
			#LoadModule cgi_module modules/mod_cgi.so
		</IfModule>
		LoadModule negotiation_module modules/mod_negotiation.so
		LoadModule dir_module modules/mod_dir.so
		LoadModule userdir_module modules/mod_userdir.so
		LoadModule alias_module modules/mod_alias.so

## php.ini (php-fpm.service)
Enabled modules `/etc/php/php.ini`

		extension=curl.so
		extension=ftp.so
		extension=gd.so
		extension=gettext.so
		extension=ldap.so
		extension=mcrypt.so
		extension=mysqli.so
		extension=pdo_mysql.so
		extension=sockets.so
		extension=zip.so

or check the installed modules:

`php -m`
		
		[PHP Modules]
		Core
		ctype
		curl
		date
		dom
		fileinfo
		filter
		ftp
		gd
		gettext
		hash
		json
		ldap
		libxml
		mbstring
		mcrypt
		mysqli
		mysqlnd
		openssl
		pcntl
		pcre
		PDO
		pdo_mysql
		Phar
		posix
		readline
		Reflection
		session
		SimpleXML
		sockets
		SPL
		standard
		tokenizer
		xml
		xmlreader
		xmlwriter
		zip
		zlib
		
		[Zend Modules]

**Comment by wayneworkman** [comment] 2016-10-11 14:09
Thank you for these notes, I'll see if I can replicate your results using these, and if I can I'll get this into the wiki. I may ask you questions though if I hit bumps.

**Comment by boban-dj** [comment] 2016-10-11 14:27
No problem, I tested it today on another machine, everythings installs correctly.
Will start cloning some machines with fog and let you know if everything also works correctly as well.

**Comment by mastacontrola** [comment] 2016-10-12 10:39
I'll see what I have in the code based tonight in regards to this.

**Comment by boban-dj** [comment] 2016-10-12 10:42
First image is successfull from archlinux as fogserver:
"Engineer","Storage Group","Storage Node","Host ID","Host Name","Host MAC","Host Desc","Image Name","Image Path","Start Date","Start Time","End Date","End Time","Duration","Deploy/Capture"
"fog","default","DefaultMember","1","Workstation1","08:00:27:d3:2d:23","Created by FOG Reg on October 12, 2016, 8:01 am","Windows7Ultimate","Windows7Ultimate","2016-10-12","08:04:06","2016-10-12","08:11:25","7 minutes 19 seconds","Capture"

**Comment by mastacontrola** [comment] 2016-10-12 10:44
https://github.com/FOGProject/fogproject/blob/working-RC-14/lib/common/functions.sh#L884

Looking here and specifically at line 893 through 921 it appears I already have the mysql_install_db from when I was running into issues.  Is your installation not making it here? Or is there an issue with it running?

**Comment by boban-dj** [comment] 2016-10-12 12:03
in 897:
`            mysql_install_db --user=mysql --ldata=/var/lib/mysql/ >>$workingdir/error_logs/fog_error_${version}.log 2>&1
`
shouldn't it be:

`sudo mysql_install_db --user=mysql --basedir=/usr --datadir=/var/lib/mysql`

Because the first install was in virtualbox, I deleted the machine and installed in real machine after with the changes, so no logs for you. I will install later today again without the changes so I can have the logs for you. thanks

**Comment by mastacontrola** [comment] 2016-10-12 12:26
The reason it's as it is currently is because that worked at the time I initially wrote it to get things working.  If I recall, the basedir defaults automatically to /usr and the library data (--ldata and/or --datadir) reference the exact same points.  Is this not working how it was originally written?

**Comment by boban-dj** [comment] 2016-10-12 12:49
No it was not working:
https://wiki.archlinux.org/index.php/MySQL#MySQL_daemon_cannot_start

mysql_install_db --user=mysql --ldata=/var/lib/mysql/

If you have datadir in /home /root or /run/user or a subdirectory of those,
from 10.1.16 onwards, due to enhanced security, you need to move your
datadir to a path or edit <https://wiki.archlinux.org/index.php/Edit>
mysqld.service to
change the default

I am not sure what the exact error was, but i let you know

In the link you can see it changed from
On Oct 12, 2016 14:26, "Tom Elliott" <notifications@github.com> wrote:
>
> The reason it's as it is currently is because that worked at the time I
initially wrote it to get things working. If I recall, the basedir defaults
automatically to /usr and the library data (--ldata and/or --datadir)
reference the exact same points. Is this not working how it was originally
written?

**Comment by mastacontrola** [comment] 2016-10-12 13:21
And now?

https://github.com/FOGProject/fogproject/blob/working-RC-14/lib/common/functions.sh

**Comment by boban-dj** [comment] 2016-10-12 13:24
Will check and let you know

**Comment by boban-dj** [comment] 2016-10-12 16:12
## For the mysql part it installed correct only these are not found

../lib/common/functions.sh: line 1565: mysql: command not found
../lib/common/functions.sh: line 1569: bc: command not found
../lib/common/functions.sh: line 1570: mysql: command not found

so installed these packages, after it was ok
	
		pacman -S bc
		pacman -S php-apache

***

## For httpd not working:

You mix up some modules,
and not comment-uncomment the right ones. Here it is better explained
<https://wiki.archlinux.org/index.php/Apache_HTTP_Server#PHP>

just for reference:

comment
		sed -i '/LoadModule rewrite_module modules\/mod_rewrite.so/s/^/#/g' file 

uncomment
		sed -i '/LoadModule rewrite_module modules\/mod_rewrite.so/s/^#//g' file 

So these should be uncommented/enabled

		sed -i '/LoadModule proxy_html_module modules\/mod_proxy_html.so/s/^#//g' /etc/httpd/conf/httpd.conf
		sed -i '/LoadModule proxy_module modules\/mod_proxy.so/s/^#//g' /etc/httpd/conf/httpd.conf
		sed -i '/LoadModule proxy_http_module modules\/mod_proxy_http.so/s/^#//g' /etc/httpd/conf/httpd.conf
		sed -i '/LoadModule proxy_fcgi_module modules\/mod_proxy_fcgi.so/s/^#//g' /etc/httpd/conf/httpd.conf


This is ok, like in the default httpd.conf, so its working with the proxy approach

		LoadModule mpm_event_module modules/mod_mpm_event.so
		#LoadModule mpm_prefork_module modules/mod_mpm_prefork.so
		#LoadModule mpm_worker_module modules/mod_mpm_worker.so


## This is what you already changed

<FilesMatch \.php$>
	SetHandler "proxy:unix:/run/php-fpm/php-fpm.sock|fcgi://127.0.0.1/"
</FilesMatch>

<IfModule dir_module>
	DirectoryIndex index.php index.html
</IfModule>



At the end it just gave me one other Building UDPCast: failed
But then I saw this machine was build with the latest 4.7.6-1 Kernel.
Because with the 4.4.24-1-lts it build fine without the UDP error


Great work!

**Comment by mastacontrola** [comment] 2016-10-12 16:22
I added the bc and php-apache packages to the arch package list, but this will only work if the fogsettings file does not already exist with the packages line within.  I'm going to go on a limb and say this is the cause for the first part of the errors.

I'm at  a loss as to why mysql command line is not working.  Did arch remove the mysql CLI command and replace with another that I'm unaware of?

**Comment by boban-dj** [comment] 2016-10-12 16:35
>  but this will only work if the fogsettings file does not already exist with the packages line within.
I am not sure what you mean, but in 1569 /lib/common/functions.sh you pipe some test to `bc`

I just installed bc and php-apache after the first part of the foginstaller, when it asked to confirm the database.

Arch cli is still mysql, no changes

**Comment by mastacontrola** [comment] 2016-10-12 16:37
So why is it mysql is failing but works when you install php-apache?

I do pipe to bc which is just a calculator so I can test, for example, 10.2 < 10.1 (or whatever).

**Comment by mastacontrola** [comment] 2016-10-12 16:37
The bc part isn't overly surprising just stating what i've done.  I will verify that it is indeed updated in working-RC-14.  I'm just updating the functions per the comment/uncomment as you suggested.

**Comment by mastacontrola** [comment] 2016-10-12 16:39
And just so you can see I am not totally nuts:

https://github.com/FOGProject/fogproject/blob/working-RC-14/lib/arch/config.sh#L16

That line is what packages are installed during the pacman -S state.  bc is indeed there and further in the list is php-apache.

**Comment by mastacontrola** [comment] 2016-10-12 16:39
functions.sh updated to have the recommended comments/uncomments for the http.conf file.

**Comment by boban-dj** [comment] 2016-10-12 16:44
Sorry but I cloned the wrong repo to vbox machine and just changed lib/common/functions.sh
So you not crazy! Thanks for the commits

**Comment by boban-dj** [comment] 2016-10-13 15:50
installed correctly from this branch only:

` * Setting up Apache and PHP files.............................../lib/common/functions.sh: line 1591: /error_logs/fog_error44.log: No such file or directory
../lib/common/functions.sh: line 1593: /error_logs/fog_error44.log: No such file or directory
../lib/common/functions.sh: line 1594: /error_logs/fog_error44.log: No such file or directory
../lib/common/functions.sh: line 1596: /error_logs/fog_error44.log: No such file or directory
../lib/common/functions.sh: line 1597: /error_logs/fog_error44.log: No such file or directory
../lib/common/functions.sh: line 1598: /error_logs/fog_error44.log: No such file or directory
../lib/common/functions.sh: line 1599: /error_logs/fog_error44.log: No such file or directory
../lib/common/functions.sh: line 1601: /error_logs/fog_error44.log: No such file or directory
../lib/common/functions.sh: line 1603: /error_logs/fog_error44.log: No such file or directory
`

when checking the httpd.conf, these below modules were still disabled in httpd.conf despite your code, I am not sure why?

/lib/common/functions.sh 1591:
`# Enable proxy
        sed -i '/LoadModule proxy_html_module modules\/mod_proxy_html.so/s/^#//g' /etc/httpd/conf/httpd.conf >>$working/error_logs/fog_error${version}.log 2>&1
        sed -i '/LoadModule proxy_module modules\/mod_proxy.so/s/^#//g' /etc/httpd/conf/httpd.conf >>$working/error_logs/fog_error${version}.log 2>&1
        sed -i '/LoadModule proxy_http_module modules\/mod_proxy_http.so/s/^#//g' /etc/httpd/conf/httpd.conf >>$working/error_logs/fog_error${version}.log 2>&1
        sed -i '/LoadModule proxy_fcgi_module modules\/mod_proxy_fcgi.so/s/^#//g' /etc/httpd/conf/httpd.conf >>$working/error_logs/fog_error${version}.log 2>&1`

**Comment by mastacontrola** [comment] 2016-10-13 16:09
Hopefully this is fixed now? (Particularly the errors I think you saw prevented the main command from running.

https://github.com/FOGProject/fogproject/commit/3c892b0b85489510d9e22382a4bd99af1ceff4c1

**Comment by mastacontrola** [comment] 2016-10-14 14:57
Closing issue for now only because I've done everything, as far as I can tell, I can do.  Hopefully I'm right in that the error writing to the file was simply preventing the whole command from running.

**Closed by mastacontrola** 2016-10-14 14:57 UTC

**Comment by boban-dj** [comment] 2016-10-14 16:02
Thanks for the suppodt
