### ISSUE TITLE
Resizeable disk grows Win10 boot partition

### ISSUE THREAD

**Issue by MilanKerslager** [FOGProject/fogproject#61] opened 2015-09-20 21:18 UTC
I tried to use resizeable image with W10 & Linux.
It worked fine, but the very first partition for booting Windows 10 was grown from 500MB to over 700MB on a bigger disc. 
The first partition has NTFS filesystem and I think it should not grow.
I have latest trunk installed (2015-09-17).

**Comment by mastacontrola** [comment] 2015-09-20 21:43
I understand what the issue is here.  The Partition, if I'm reading this right, shouldn't be expanding at all?  I don't know what this even means though.  Everything is working, and you're submitting an issue to describe the partition is growing though you're not expecting them too?

For right now, I'm closing this ticket. If things were not working, I'd be trying to figure it out, but as you stated everything is working, and the size of the problematic partition is only growing by 200 megs, I don't see it too much a problem.

**Closed by mastacontrola** 2015-09-20 21:43 UTC
