### ISSUE TITLE
quick image failes with error chainloading failed.

### ISSUE THREAD

**Issue by vipconsult** [FOGProject/fogproject#96] opened 2016-04-12 11:38 UTC
Here is a short video of the error
http://screencast.com/t/0bxQ2lsQG9mT

this is the latest fog version from git and updated using the installation script.

**Comment by mastacontrola** [comment] 2016-04-12 15:54
I cannot replicate this problem in any shape or form, but mostly that could be because I don't have the same operating environment as you do.

Can you try replacing the ROM for the systems NIC to something compiled by the iPXE team and see if that helps you out?

**Comment by vipconsult** [comment] 2016-04-12 15:57
I have tried it on few different machines with the same result.

Do you know what does this error usually mean ?

I suspect something went wrong with from the Version: 5046 update.

**Comment by Nekroze** [comment] 2016-04-25 23:34
@vipconsult I am having the exact same problem except it takes longer before it actually fails and happens not just when doing a quick image but when performing any imaging task (download or capture).

I have to get the FOG system working again (sadly we do not have a staging environment for testing fog updates (yet)), does anyone know a git commit that predates this issue that I can revert to in the mean time?

**Comment by vipconsult** [comment] 2016-04-25 23:43
Yes it does the same with me as well  on download and capture. @mastacontrola is  pointing me to the ipxe firmware , but I think the problem is somewhere else as the same machines work fine on Version: 5046

@mastacontrola : do you know what   does this error actually mean ?

**Comment by Nekroze** [comment] 2016-04-26 00:16
@vipconsult 5046 is pretty far back now, I am not sure if the database will survive a rollback like that so I might stick with it or just re-install 1.2 stable and stay there this time.

The problem might (sorry just a wild guess here) this line in the output of `/fog/service/ipxe/boot.php`:
chain -ar http://fogserver/fog/service/ipxe/boot.php##params

The errors seem to be about failing to chainload and as far as I can tell this is what is meant to do it but that url especially the "##params" bit seems wrong. Perhaps this is your input/output error?

**Comment by Nekroze** [comment] 2016-04-26 01:00
@mastacontrola Also as far as operating environment is concerned, while @vipconsult may have a setup a bit outside of the norm, I am experiencing this on a centos 6 machine with real physical client machines.

**Comment by vipconsult** [comment] 2016-04-26 01:02
I tested this on few real machines as well with the same result.

**Comment by mastacontrola** [comment] 2016-04-26 10:07
What version are you all running?  I need to know the exact version as in the cloud (or the SVN version as found under FOG Configuration Page.

**Comment by vipconsult** [comment] 2016-04-26 10:11
I was running the latest one at the time I submitted the ticket and now reverted back to the last stable one

**Comment by mastacontrola** [comment] 2016-04-26 10:40
What do you mean?

If you were on the "latest" 14 days ago, that's different than things from current.  I can't fix what I can't replicate, but I also can't fix what others are reporting if you just revert back.

While I understand the operational requirement, more info is still needed before I can come up with a fix, or at least understand what/why this may be happening.

For the both of you, does this ONLY happen on VMs?

**Comment by darksidemilk** [comment] 2016-04-26 12:51
A few reccomendations, update to the latest git, a lot has changed in 14 days. Try using ipxe.kpxe or ipxe.kkpxe as the bootfile. Also set the exit type to anything that isn't exit. I see that error with the exit type exit.

**Comment by Nekroze** [comment] 2016-04-26 22:52
@darksidemilk I thought ipxe.kpxe and the like where loaded by the undionly.kpxe or is that just because the docs don't match the dev branch? Can I change the DHCP server to ipxe.kpxe or ipxe.kkpxe and what is the difference?

@mastacontrola I experienced this issue with the latest dev-branch commits as of yesterday so if you want one in particular then d830052e69c434c8c8dcbca14b73bd947c99e435 (fog version 7302)  was one of the versions. I am now running 7174 as it was the closest I could find within a reasonable amount of time (I tried a lot of versions) that was not affected by this or other issues that are already solved upstream, somewhere.

Also no I am not PXE booting VM's, just physical machines.

**Comment by darksidemilk** [comment] 2016-04-27 00:08
From what I understand it was the other way around, ipxe.kpxe contains undionly.kpxe. I saw it in the ipxe forums or docs somewhere. The kkpxe is used for devices that don't work with kpxe. You can just change it in the dhcp setting and that's all there is to it. You can also make a dhcp reservation and set it individually as needed. 




Sent from Outlook Mobile






On Tue, Apr 26, 2016 at 3:52 PM -0700, "Nekroze" <notifications@github.com> wrote:












@darksidemilk I thought ipxe.kpxe and the like where loaded by the undionly.kpxe or is that just because the docs don't match the dev branch? Can I change the DHCP server to ipxe.kpxe or ipxe.kkpxe and what is the difference?



@mastacontrola I experienced this issue with the latest dev-branch commits as of yesterday so if you want one in particular then d830052 (fog version 7302)  was one of the versions. I am now running 7174 as it was the closest I could find within a reasonable amount of time (I tried a lot of versions) that was not affected by this or other issues that are already solved upstream, somewhere.



Also no I am not PXE booting VM's, just physical machines.

**Comment by Nekroze** [comment] 2016-04-27 00:15
@darksidemilk Ok, looks like I have some more testing to do in the future with ipxe files to pxe boot to and maybe also test these exit commands, never really looked into the alternative options for either of these.

**Comment by mastacontrola** [comment] 2016-05-01 01:10
I'm normally only aware of the chainloading problem when hosts are booting to HDD's.  The "Fix" if you will is to change out the default method of booting to the hard drive.  The "default" FOG falls to is sanboot 0x80, though this doesn't always work.  The next, often times, would be to use exit type.  The problem with exit is if your device is UEFI and you booted to the iPXE menu using legacy, the swap doesn't handle switching from BIOS to UEFI, so the best fix I can think of for that is to keep the network boot layer the same as the expected method of the system HDD boot.

Other issues might come from errors in code, though I do typically know about those relatively quickly.  Either that or there's a problem in the ipxe code itself (which I don't know anything about myself).

**Comment by Nekroze** [comment] 2016-05-04 00:31
@mastacontrola I am using the default exit (so sanboot) and already have both fog and the hard drive booting in legacy mode as I have yet to get FOG PXE booting without legacy booting everything. Also FOG seems to not like the multiple partitions required for the EFI partition, at least with windows but that's a separate issue.

**Comment by darksidemilk** [comment] 2016-05-04 14:41
I would try one of the GRUB exit options. Also, FOG has no problems with
the extra partitions for EFI (or mbr for that matter), it used to be that
you had to have only one partition to make it resizable but that's not the
case in the more recent releases.
Can you get FOG PXE booting working (with or without efi) outside of
docker? I would want to know it's configured right for its intended use
before trying to make changes to it.
What kind of DHCP server are you using and how are you configuring it for
fog pxe booting?
In my experience, for efi pxe booting, it is as simple as switching the pxe
bootfile from a .kpxe or .kkpxe file to a .efi pxe file.

Also, what kind of PC architecture is this docker system running on? As in
Intel or AMD and 64 bit or 32 bit? I made a recent discovery on pxe
bootfiles that ipxe.kkpxe (or undionly.kkpxe) is required for amd computers
to boot to pxe. Most intel computers will also boot with kkpxe, but a
select few have issues with exiting pxe, especially to local hard drive. So
I have my default boot set to ipxe.kpxe and make dhcp reservations for the
exceptions and set static boot file options for them.
If you haven't already, try switching to ipxe.kkpxe and ipxe.kpxe. Also
what kind of virtual network card is being used?

I realize docker is a bit different than say a VMware esxi environment, but
considering that I've got fog working reliably in esxi, on vmware
workstations, and on physical machines, and I've seen it work on virtual
box, I'm willing to bet that this just kind of will work with just a few
configuration changes. But I could be wrong. Could you give me a quick
tutorial on how to set up a comparable docker setup to test this out in a
different environment for you?


Also, I would strongly suggest putting all this in the forums at
https://forums.fogproject.org/. That will give you a bigger team of people
ready and willing to help.

**Comment by mastacontrola** [comment] 2016-05-09 10:37
@Nekroze What version of FOG are you using?  The trunk versions handle multiple partitions rather nicely compared to olden times.

**Comment by Nekroze** [comment] 2016-05-10 23:00
@mastacontrola I am now using 7174 and have yet to update again since the last set of issues caused by updating. I thought that it was meant to be better with multiple partitions in the later versions but I have still had issues, even very recently. I have been working on a windows 10 image and FOG tried to upload the entire 500Gb hard drive rather than shrinking it first when I had two partitions. I have also had some problems with it not booting with the standard post windows 7 small boot partition alongside a larger ntfs partition, although intermittant.

If FOG should be able to overcome these issues now then I will re-investigate using UEFI and multiple partitions for my deployments which would be better as at the moment I have to manually revert all machines back to legacy booting and all that which is disabled by default on modern hardware.

Would FOG have issues with Secure Boot enabled? Would it not allow pxe booting without disabling Secure Boot or is there some extra steps that are required.

@darksidemilk Interesting I will look into EFI pxe booting with some of that info. However, I did not mention docker, I have FOG deployed on a CentOS 6 box.

**Comment by mastacontrola** [comment] 2016-05-11 11:52
Secure boot, and any imaging software, will most likely have issues.

**Comment by Nekroze** [comment] 2016-05-12 02:10
@mastacontrola I have UEFI booting working now and while secure boot does not work it is much less of a change to the UEFI configuration to just temporarily disable it for imaging. I am working on a new UEFI booting image now with windows 10, hopefully it wont have problems capturing it.

In looking into it there has been some talk of iPXE getting signed for secure boot but no one seems to care too much, which is a shame because it seems Microsoft are enforcing OEM machines be configured to use secure boot and will not allow the OEM to disable that.

**Comment by mastacontrola** [comment] 2016-05-17 17:18
I have not run into a system where secure boot was forcibly enabled.  Meaning, while Windows prefers Secure boot be enabled while the OS is loading (which is perfectly understandable) during imaging (upload or download) disabling the secure boot is much simpler than having to try to sign a simple little binary.

The methods that most tend to use for UEFI that I've found as most successful is before any imaging task, disable secure boot.  After the imaging task is completed, re-enable secure boot.

**Comment by Nekroze** [comment] 2016-05-19 00:24
@mastacontrola Indeed I am using that workflow now (disable secure boot while imaging only). No machines are forced to have Secure Boot enabled when running, I was trying to say that hardware manufacturers have been told by Microsoft that they are not allowed to disable secure boot on their BIOS/UEFI if windows 10 is installed when the device gets shipped to the customer.

Where I work we get the OEM PC manufacturer (a very popular business computer company) who where providing custom BIOS settings for us in the past that allowed us to unbox and start imaging instantly. This is no longer possible as they are not allowed to disable secure boot as per their agreement with Microsoft and if we have to go and change one BIOS setting manually each time we unbox a new computer to image (2 to 10 computers a week on average) we may as well change the other settings ourselves as well rather than pay extra for half the BIOS to be correctly configured.

This is a shame because when imaging large quantities of computers with FOG it is very helpful to have them ready to take an image the moment we unbox them as changing BIOS settings for 10 computers before you can image them takes time and is made more slow/annoying by a poor KVM. Would be nice to have this workflow back but it would require a signed iPXE for the foreseeable future which sucks a bit because no one seems to care about getting things signed for Secure Boot. The only good documentation I have found for it is for Gentoo and its quite complex and still requires a custom bios/UEFI setup anyway because you need to have it accept your key if you don't want to pay for access to Microsoft's key or whoever owns the one that computers come with.

The whole secure boot thing is just sad, its a solid idea but its execution has baked in elitism by shipping MS keys only making MS the only people who can secure boot, for now, without having to reconfigure the UEFI.

My apologies for the pseudo-rant.

**Comment by Sebastian-Roth** [comment] 2016-05-19 04:56
While I totally understand that this is very annoying for you I think there is not much we can do from the FOG side. That said I am still happy to do some research and maybe help you when it comes to the toolchain of signing request and that stuff.

The iPXE devs seem to have put in some work to get it done. Sounds like it can be done when you can spend US$ 500. Plus you need to wait for Microsoft to sign your binary - which seems to take weeks... http://ipxe.org/appnote/etoken
As well you might want to read through those posts: http://forum.ipxe.org/showthread.php?tid=7843, http://forum.ipxe.org/showthread.php?tid=7261
Please let us know before you think about actually signing a binary. We should talk about the version and the embedded script code used as you can't simply change anything without going through the process of re-signing again. So the iPXE EFI binary should be well tested on a wide range of your PCs beforehand.

And there might be another option for you. In this thread (http://forum.ipxe.org/showthread.php?tid=7533) one of the lead devs is saying:
> By default, UEFI does not apply SecureBoot checks to binaries present in NIC ROMs, which reduces the utility of having a signed version of iPXE; it's only chainloading that would really benefit.

So if you can talk to OEM PC manufacturer to supply the PCs with iPXE burned into the NIC ROMs you should be going fine. Haven't tested this myself but I've read of people doing it (not for the purpose of secure booting but).

**Comment by Nekroze** [comment] 2016-05-19 09:29
@Sebastian-Roth I completely understand its not FOG's fault. Just wanted to let someone know about the pitfalls I found moving to UEFI with FOG. There is a better place for this so I will end that there to stay on topic.

Tomorrow morning there is a full snapshot scheduled of my FOG server so I will perform and update to explore if this issue persists or has been resolved.

**Comment by Nekroze** [comment] 2016-05-24 01:18
I have upgraded from 7174 to 7777 with no hiccups and all previously experienced issues are no longer present (as far as I can tell) in version 7777.

**Closed** 2016-06-01 16:29 UTC

**Comment by lreddy3006** [comment] 2021-08-04 16:14
Hi All,
In FOG, am using Ubuntu ISO with PXE network boot installation, but getting "ChainLoading failed hits for the ipxe shell" from the console. Please help me on this.

**Comment by Sebastian-Roth** [comment] 2021-08-07 06:13
@lreddy3006 No idea what your post has to do with this very old topic. You are better off posting a new topic in the [FOG forums](https://forums.fogproject.org).
