### ISSUE TITLE
Installation ignores many inputs

### ISSUE THREAD

**Issue by AccidentallyTheCable** [FOGProject/fogproject#288] opened 2019-01-31 21:51 UTC
First time with fog. Fresh install. Command line opts:

/home/automation/foginstall/fogproject-1.5.5/bin/installfog.sh -S -C -Y -s 10.20.24.32 -e 10.20.24.254 -c /etc/ssl/certs/fog/

Config output:

ipaddress='10.95.192.192'
copybackold='0'
interface='enp0s18'
submask='255.255.255.0'
routeraddress='10.95.192.1'
plainrouter='10.95.192.1'
dnsaddress='208.67.222.222'
username='<redacted>'
password='<redacted>'
osid='1'
osname='Redhat'
dodhcp='N'
bldhcp='0'
dhcpd='dhcpd'
blexports='1'
installtype='N'
snmysqluser='root'
snmysqlpass=''
snmysqlhost='localhost'
installlang='0'
storageLocation='/images'
fogupdateloaded=1
docroot='/var/www/html/'
webroot='/fog/'
caCreated='yes'
httpproto='https'
startrange=''
endrange=''
bootfilename='undionly.kpxe'
packages='bc curl gcc gcc-c++ genisoimage gzip httpd lftp m4 make mariadb mariadb-server mod_ssl mtools net-tools nfs-utils php php-bcmath php-cli php-common php-fpm php-gd php-ldap php-mbstring php-mysqlnd php-process syslinux tar tftp-server unzip vsftpd wget xinetd xz-devel '
noTftpBuild=''
notpxedefaultfile=''
sslpath='/opt/fog/snapins/ssl/'
backupPath='/home/'
php_ver=''
php_verAdds=''
sslprivkey='/opt/fog/snapins/ssl//.srvprivate.key'

**Comment by Sebastian-Roth** [comment] 2019-02-02 23:04
@AccidentallyTheCable Thanks for letting us know. Most installer options have not been used much by users in the last years and therefore didn't get much of our attention. The whole thing could take a major re-work but we definitely won't get into that for FOG 1.5.x but let's see what we can do to make this work for you.

1. DHCP options - start/end range - Those were not taken into account as the installer does **not** install/configure DHCP by default. Sure it should when start/end range are used and I just pushed fixes to the dev-branch to solve that - 0bfc4a8 and b5744f5
2. SSL path option needed minor fixing as well - 8be015e
3. `username` and `password` are empty in your example - I guess you intentionally blanked those as I cannot reproduce this in my test install
4. Note that using the `dev-branch` you don't need to run the build script for iPXE binaries anymore when installing FOG with `-S/--force-https` option. It's done automatically now.

**Comment by Sebastian-Roth** [comment] 2019-02-07 09:32
@AccidentallyTheCable As I have not had any complains about this an you posted new stuff, I'll close this issue for now.

**Closed by Sebastian-Roth** 2019-02-07 09:32 UTC
