### ISSUE TITLE
FOG with installation on UEFI on a M2 disk

### ISSUE THREAD

**Issue by mrpouletcurry** [FOGProject/fogproject#386] opened 2020-04-21 09:31 UTC
Problems after deployment any Linux image in a **UEFI M2 disk**. 
After deployment the system doesn't work, the files seem to be corrupted.

The system deployed was Linux.

**Comment by Sebastian-Roth** [comment] 2020-04-21 10:31
@mrpouletcurry said:
> the files seem to be corrupted

What do you mean by that. Can you provide more information on this. Any error messages you get? Please take a picture of the screen and post here.

As well I have a few more questions:
* What image type do you use (resizable or non-resizable)?
* Is the new M2 disk 4k block size?
* What does the partition layout look like? Post the contents of `d1.partitions` text file you find in the image directory on your FOG server.

**Comment by Sebastian-Roth** [comment] 2020-04-26 17:04
@mrpouletcurry Please provide more information.

**Comment by Sebastian-Roth** [comment] 2020-05-08 14:34
@mrpouletcurry We are closing this issue now as we don't have enough information to work on. Feel free to reply even though the issue is closed and we will pick this up again.

**Closed by Sebastian-Roth** 2020-05-08 14:34 UTC
