### ISSUE TITLE
FTP rename issue

### ISSUE THREAD

**Issue by xeebuc** [FOGProject/fogproject#657] opened 2024-11-14 18:41 UTC
Hello,

Since the last update we did we have an issue with the capture.
The last step should be to move the captured images from /images/dev/MACADDRESS to /images/NAME_of_images
But that step failed.

See attachement for FTP log
[for_ftp_log.log](https://github.com/user-attachments/files/17756223/for_ftp_log.log)

/images content:
![image](https://github.com/user-attachments/assets/b027338c-63d6-4cd9-be7d-e29f3d32076f)

Server:
Debian 12
Fog 1.5.10 1615

/etc/vsftd.config : 

```shell
max_per_ip=200
anonymous_enable=NO
local_enable=YES
write_enable=YES
local_umask=022
dirmessage_enable=YES
connect_from_port_20=YES
listen=YES
pam_service_name=vsftpd
userlist_enable=NO
tcp_wrappers=YES
seccomp_sandbox=NO

xferlog_std_format=YES
xferlog_enable=YES

log_ftp_protocol=YES
vsftpd_log_file=/var/log/vsftpd.log
syslog_enable=NO
dual_log_enable=YES
``` 

Any idea ?

**Comment by mastacontrola** [comment] 2024-11-18 11:15
Can you try to ensure your images folder is entirely 777 permissions recursively please?

```
chmod -R 777 /images
```

and try again. I know we want more security but it seems something else might be causing it and just seeing if this simple change corrects that isn't, in my opinion, overly bad unless you still have open NFS permissions with root privileges, which you shouldn't since you're running 1615

**Comment by xeebuc** [comment] 2024-11-18 15:06
Hi,

Just tried it. didn't worked :(

**Comment by osiktech** [comment] 2024-11-18 15:22
Hi @xeebuc,

I was going through the logfile you provided. I believe the problem is not the move but removing the old image plus folder. 

Check line 15 of the log, it says:

```
Thu Nov 14 13:19:49 2024 [pid 2043093] [fogproject] FAIL RMDIR: Client "10.X.X.X", "/images/TemplateLenovoEN"
```

Also TemplateLenovoEN is a file and not a folder according to your screenshot.

Did you maybe manually delete the image folder before? Or did a capturing failed before?

Maybe you could remove the image in the fog webinterface, then recreate it and finally assign it again?!

**Comment by xeebuc** [comment] 2024-11-18 15:28
Hi Osiktech,

TemplateLenovoEN was a folder (existing capture), but after failling the move / rename /remove... it become a file
We are trying to override an existing capture.

Regards,

**Comment by osiktech** [comment] 2024-11-18 16:10
@xeebuc In this case, my recommendation to make it work again. drop the current image in the fog web interface. make sure to note which hosts are using this image. create a temporary group with these hosts.

create a new image and capture it. After the capture assign this image to the above mentioned temporary group. In the end you can remove the group in the web interface again.

Hope this helps.

**Comment by xeebuc** [comment] 2024-11-18 16:25
Hum.

Just tried to capture on new name ... same issue
And also , we are trying to use scheduled task for the capture, so at the end the image will always be overwrited

**Comment by darksidemilk** [comment] 2024-11-18 17:00
Instead of removing the image in the web gui/database, try just removing the file on the server if you didn't remove the file.
There were some issues with the removal before replacing the old image with the new one at one point. This would be doing like `rm -fr /images/TemplateLenovoEN` just be sure you have the right image name there. Then try to capture the image as if it was brand new. You could also try changing the image path setting on the image definition in the web gui so it captures to a new location. This wouldn't be the permanent solution just debugging to see where to look for the problem. 

You can also try using FOG 1.6 as we have recently added some resiliency against issues like this

**Comment by xeebuc** [comment] 2024-11-18 19:10
Okay, so i did another test on a different environnement (test lab) . 
And it work well (same version)

What i've notice is that the folder/image created is under the owner fogproject (vs root in the non working case).
Why the image is created with the owner root ? and how I change that ?

**Comment by xeebuc** [comment] 2024-11-18 19:48
Okay so I found the issue (thanks @mastacontrola for your mention of NFS)
Basicaly i've edited the /etc/exports files (same as my test setup witch is functionnal) 
![image](https://github.com/user-attachments/assets/3493360e-04b2-4105-9d59-4e3508985b22)

And then test a capture... 
![image](https://github.com/user-attachments/assets/3121332e-fdaa-4409-a757-a28be64d5a8d)

WORKING ! 


Suggestion, Edit those pages to add a section about the /etc/exports file
- https://wiki.fogproject.org/wiki/index.php?title=Troubleshoot_FTP
- https://docs.fogproject.org/en/latest/kb/troubleshooting/troubleshoot-ftp/

Thanks,

**Closed as completed** 2024-11-18 20:00 UTC
